---
fullnameOverride: "web"
image:
  repository: p6rguvyrst/instrumentation-demo
  tag: v0.1.0
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8000
environment:
  variables:
    - name: SENTRY_DSN
      value: "%%SENTRY_DSN%%"
resources:
  limits:
    cpu: 200m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 1024Mi
##ingress:
#  enabled: true
#  annotations:
#    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
#    certmanager.k8s.io/acme-challenge-type: http01
#    kubernetes.io/ingress.class: "nginx"
#    kubernetes.io/tls-acme: "true"
#    kubernetes.io/ssl-redirect: "true"
#  hosts:
#    - host: demo.verypythonproblems.com
#      paths:
#        - /
#  tls:
#    - secretName: tls-demo-verypythonproblems
#      hosts:
#        - demo.verypythonproblems.com
