---
kubeStateMetrics:
  enabled: true
alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 1Gi
  service:
    type: NodePort
nodeExporter:
  enabled: true
  tolerations:
    - effect: "NoSchedule"
      operator: "Exists"
pushgateway:
  enabled: false
server:
  enabled: true
  global:
    external_labels:
      cluster: k8s-london
  persistentVolume:
    enabled: true
    mountPath: /data
    size: 2Gi
  service:
    type: NodePort
  extraArgs:
    storage.tsdb.retention: 3d
    storage.tsdb.max-block-duration: 2h
    storage.tsdb.min-block-duration: 2h
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
extraScrapeConfigs: |-
  - job_name: 'prometheus-endpoints'
    scrape_interval: 20s
    scrape_timeout: 5s
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node
