{
 "title": "Kubernetes Namespace Insight",
 "description": "Aggregated Insight Powered by Prometheus, Elasticsearch and Alertmanager.",
 "tags": [
  "elasticsearch",
  "prometheus",
  "alertmanager",
  "k8s",
  "namespace",
  "utilization",
  "usage",
  "cost"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "alertmanager",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   { "name": "elasticsearch", "query": "elasticsearch" },
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "app",
    "query": "label_values(kube_pod_labels, label_app)"
   },
   {
    "name": "cpu_price",
    "query": "19.5275,12.80208333,8.440972222"
   },
   {
    "name": "ram_price",
    "query": "4.881875,3.200520833,2.110243056"
   },
   { "name": "log_price", "query": "0" },
   { "name": "pv_price", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Cost of Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"[[namespace]].*\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"[[namespace]].*\"})"
    }
   ]
  },
  {
   "title": "Requested CPU (monthly)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 1 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"[[namespace]].*\"})*$cpu_price"
    }
   ]
  },
  {
   "title": "RAM Budget Utilisation (monthly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"[[namespace]].*\"})/1024/1024/1024)*$ram_price",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"[[namespace]].*\"})/1024/1024/1024)*$ram_price",
     "legendFormat": "Limits"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=~\"[[namespace]].*\"})/1024/1024/1024)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"[[namespace]].*\"})"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"[[namespace]].*\"})"
    }
   ]
  },
  {
   "title": "Requested RAM (monthly)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 6 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"[[namespace]].*\"})/1024/1024/1024)*$ram_price"
    }
   ]
  },
  {
   "title": "CPU Budget Utilisation (monthly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"[[namespace]].*\"}))*$cpu_price",
     "legendFormat": "Limits"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"[[namespace]].*\"}))*$cpu_price",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m]))*$cpu_price",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Resource Utilisation (requests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Memory Utilisation %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{namespace=~\"[[namespace]].*\"}) by (container_name) / sum(label_join(kube_pod_container_resource_requests_memory_bytes{namespace=~\"[[namespace]].*\"},\n    \"container_name\", \"\", \"container\")) by (container_name)) * 100",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Container CPU Utilisation %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace=~\"[[namespace]].*\"}[5m])) by (container_name) / sum(label_join(kube_pod_container_resource_requests_cpu_cores{namespace=~\"[[namespace]].*\"},\n    \"container_name\", \"\", \"container\")) by (container_name)) * 100",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilisation (limits)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Memory Utilisation %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{namespace=~\"[[namespace]].*\"}) by (container_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace=~\"[[namespace]].*\"},\n    \"container_name\", \"\", \"container\")) by (container_name)) * 100",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Container CPU Utilisation %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace=~\"[[namespace]].*\"}[5m])) by (container_name) / sum(label_join(kube_pod_container_resource_limits_cpu_cores{namespace=~\"[[namespace]].*\"},\n    \"container_name\", \"\", \"container\")) by (container_name)) * 100",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Resource Usage (total)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"[[namespace]].*\"}[5m])) by (pod_name, namespace)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"[[namespace]].*\"}) by (pod_name, namespace)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Resource Usage (total)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container  CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_name!=\"POD\", container_name!=\"\", namespace=~\"$namespace\"}[5m])) by (container_name, namespace)",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Container Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", container_name!=\"\", namespace=~\"$namespace\"}) by (container_name, namespace)",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space used (%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(kubelet_volume_stats_used_bytes{namespace=~\"[[namespace]].*\"}) by (persistentvolumeclaim) / \n sum(kubelet_volume_stats_capacity_bytes{namespace=~\"[[namespace]].*\"}) by (persistentvolumeclaim)) * 100",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Disk space available (bytes)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_available_bytes{namespace=~\"[[namespace]].*\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "stderr",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "kubernetes.namespace_name:$namespace AND stream:stderr",
       "timeField": "@timestamp"
      },
      {
       "alias": "stdout",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "kubernetes.namespace_name:$namespace AND stream:stdout",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$namespace stderr",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "kubernetes.namespace_name:$namespace AND stream:stderr",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}