{
 "title": "a Django Prometheus new",
 "description": "Django metrics dashboard using korfuri/django-prometheus Prometheus metrics exporter",
 "tags": [
  "django",
  "python",
  "app"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(django_db_new_connections_total, namespace)"
   },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(django_db_new_connections_total{namespace=~\"$namespace\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python version",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "python_info{namespace=~\"[[namespace]].*\", app=~\"[[app]].*\"}",
       "legendFormat": "{{implementation }} {{version}}"
      }
     ]
    }
   ]
  },
  { "title": "Django Models Instrumentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Django Models",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(django_model_count_total{namespace=~\"[[namespace]].*\"}) by (model)",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Django Default Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "singlestat",
     "description": "increase(v range-vector) calculates the increase in the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. The increase is extrapolated to cover the full time range as specified in the range vector selector, so that it is possible to get a non-integer result even if a counter increases only by integer increments.",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(django_http_requests_total_by_transport_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
      }
     ]
    },
    {
     "title": "2XX Responses",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
      }
     ]
    },
    {
     "title": "4XX Responses",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\",namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
      }
     ]
    },
    {
     "title": "5XX Responses",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\",namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[1m])) by(method, view)",
       "legendFormat": "{{method}} /{{view}}"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
       "legendFormat": "quantile=50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
       "legendFormat": "quantile=95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
       "legendFormat": "quantile=99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
       "legendFormat": "quantile=99.9"
      }
     ]
    },
    {
     "title": "Responses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(django_http_responses_before_middlewares_total{namespace=~\"$namespace\", app=~\"^$app$\", view!~\"prometheus-django-metrics|healthcheck\"}[1m])) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Response Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(django_http_responses_total_by_status_total{namespace=~\"$namespace\", app=~\"^$app$\", view!~\"prometheus-django-metrics|healthcheck\"}[1m])) by(status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Database Ops",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(django_db_execute_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (vendor)",
       "legendFormat": "{{vendor}}"
      }
     ]
    },
    {
     "title": "Models stats",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(django_model_deletes_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (model)",
       "legendFormat": "[{{model}}] deletes"
      },
      {
       "expr": "sum(irate(django_model_inserts_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (model)",
       "legendFormat": "[{{model}}] inserts"
      },
      {
       "expr": "sum(irate(django_model_updates_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (model)",
       "legendFormat": "[{{model}}] updates"
      }
     ]
    }
   ]
  },
  {
   "title": "Python Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Garbage collections (rate)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_collections_total{namespace=~\"[[namespace]].*\", app=~\"[[app]].*\"}[1m])",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Garbage collection (uncollectable)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_gc_objects_uncollectable_total{namespace=~\"[[namespace]].*\", app=~\"[[app]].*\"}",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    },
    {
     "title": "Garbage collection (collected)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_gc_objects_collected_total{namespace=~\"[[namespace]].*\", app=~\"[[app]].*\"}",
       "legendFormat": "Generation {{generation}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "kubernetes.namespace_name:$namespace",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}